version: '3.8'
services:
  site1:
    build: site1/storage-xss
    ports:
      - "60012:9090"

  site3:
    image: nginx:alpine
    volumes:
      - ./site3:/usr/share/nginx/html
    ports:
      - "60013:80"
