version: '3.8'
services:
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "6080:9090"

  mysql_db:
    image: mysql:8
    ports:
      - "6033:3306"
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test